version: '3.8'
services:
  production:
    build:
      context: .
      args:
        DEPLOY_ENV: production
    ports:
      - '3000:3000'

  staging:
    build:
      context: .
      args:
        DEPLOY_ENV: staging
    ports:
      - '4000:3000' # Different port for staging
