name: GAE Pipeline

on:
  push:
    branches:
      - master
      - develop

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v3
      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      ## Install dependencies
      - name: yarn install
        run: |
          yarn install 
          yarn install -g firebase-tools --legacy-peer-deps
      ## Build & Deploy Staging
      - name: Build & Deploy Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          yarn build:staging
          firebase deploy --only hosting -P staging --token ${{ SECRETS.FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"
      ## Build & Deploy Production
      - name: Build & Deploy Production
        if: github.ref == 'refs/heads/master'
        run: |
          yarn build
          firebase deploy --only hosting -P production --token ${{ SECRETS.FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"
